#!/usr/bin/env python3
"""
EMAIL GENERATOR MODULE
Subsystem 3 — Intelligent Auto Courier Email System
ICT304 — Warehouse Intelligence System

Fixed-template email generator + SMTP sender (simulation mode).
No AI/NLP — straightforward rule-based templates.
"""

import random
import smtplib
from datetime import datetime, timedelta
from typing import Dict, List, Optional
from dataclasses import dataclass, asdict
from enum import Enum
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

from order_database import WAREHOUSE_INFO
from ai_decision_engine import COURIER, COURIER_EMAIL


# ============================================================================
# CONFIGURATION
# ============================================================================

EMAIL_CONFIG = {
    "smtp_server": "smtp.gmail.com",
    "smtp_port": 587,
    "use_tls": True,
    "sender_email": "warehouse.system@smartwarehouse.com",
    "sender_name": "Smart Inventory System",
    "max_retries": 3,
    "simulation_mode": True
}


# ============================================================================
# DATA MODELS
# ============================================================================

class EmailStatus(Enum):
    PENDING = "pending"
    SENT = "sent"
    FAILED = "failed"


@dataclass
class EmailLog:
    """Log entry for email transmission."""
    log_id: str
    order_id: str
    timestamp: str
    status: str
    recipient: str
    subject: str
    details: str = ""


# ============================================================================
# EMAIL GENERATOR (FIXED TEMPLATE)
# ============================================================================

class EmailGenerator:
    """
    Rule-based email generator using fixed templates.
    No AI/NLP — clean and deterministic.
    """

    def generate(self, order, decision) -> Dict:
        """
        Generate a complete pickup request email.

        Args:
            order: Order from order_database
            decision: ShippingDecision from ai_decision_engine

        Returns:
            Dict with 'subject', 'body', 'to', 'from'
        """
        pickup_time = self._get_pickup_time(decision.shipping_method)
        fragile_note = self._get_fragile_note(decision.is_fragile)

        subject = (
            f"Pickup Request — Order {order.order_id} | "
            f"FedEx {decision.shipping_method}"
        )
        if decision.is_fragile:
            subject += " [FRAGILE]"

        body = f"""Dear FedEx Logistics Team,

We would like to request a pickup for the following shipment.

{'=' * 50}
  SHIPMENT DETAILS
{'=' * 50}

  Order ID:        {order.order_id}
  Shipping Method: {decision.shipping_method}
  Courier:         FedEx

{'─' * 50}
  PACKAGE INFORMATION
{'─' * 50}

  Weight:          {order.weight_kg} kg
  Dimensions:      {order.dimensions_str}
  Volume:          {order.volume_cm3:,.0f} cm³
  Contents:        {order.product_name} ({order.product_category})
  Item Count:      {order.item_count}
  Declared Value:  {order.currency} {order.declared_value:,.2f}
{fragile_note}
{'─' * 50}
  DESTINATION
{'─' * 50}

  Recipient:       {order.contact_name}
  Address:         {order.destination_address}
  Country:         {order.destination_country}
  Postcode:        {order.destination_postcode}
  Email:           {order.contact_email}
  Phone:           {order.contact_phone}

{'─' * 50}
  PICKUP DETAILS
{'─' * 50}

  Pickup Location: {WAREHOUSE_INFO['address']}
  Dock Number:     {WAREHOUSE_INFO['dock_number']}
  Requested Time:  {pickup_time}
  Operating Hours: {WAREHOUSE_INFO['operating_hours']}
  Contact:         {WAREHOUSE_INFO['contact']}

{'=' * 50}

Please confirm the pickup schedule at your earliest convenience.

Regards,
{EMAIL_CONFIG['sender_name']}
{WAREHOUSE_INFO['name']}
{WAREHOUSE_INFO['address']}
Tel: {WAREHOUSE_INFO['contact']}

---
Auto-generated by Smart Warehouse Intelligence System
{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""

        return {
            "subject": subject,
            "body": body,
            "to": COURIER_EMAIL,
            "from": f"{EMAIL_CONFIG['sender_name']} <{EMAIL_CONFIG['sender_email']}>",
            "courier": COURIER,
            "pickup_time": pickup_time
        }

    def _get_pickup_time(self, method: str) -> str:
        now = datetime.now()
        if method == "Same-Day":
            t = now + timedelta(hours=1)
            return t.strftime("%Y-%m-%d %H:%M") + " (IMMEDIATE)"
        elif method == "Express":
            if now.hour < 14:
                t = now.replace(hour=16, minute=0)
            else:
                t = (now + timedelta(days=1)).replace(hour=9, minute=0)
            return t.strftime("%Y-%m-%d %H:%M")
        else:
            t = (now + timedelta(days=1)).replace(hour=9, minute=0)
            return t.strftime("%Y-%m-%d %H:%M")

    def _get_fragile_note(self, is_fragile: bool) -> str:
        if is_fragile:
            return (
                "\n  ⚠️  FRAGILE — Handle with care. Do not stack.\n"
                "  Special packaging required during transit.\n"
            )
        return ""


# ============================================================================
# EMAIL SENDER (SIMULATION MODE)
# ============================================================================

class EmailSender:
    """Handles email transmission with retry and simulation support."""

    def __init__(self):
        self.logs: List[EmailLog] = []
        self._counter = 0

    def send(self, email_data: Dict, order_id: str) -> Dict:
        """
        Send (or simulate sending) the pickup request email.

        Returns:
            Dict with 'success', 'status', 'message'
        """
        self._counter += 1

        if EMAIL_CONFIG["simulation_mode"]:
            success = self._simulate(email_data)
        else:
            success = self._real_send(email_data)

        status = EmailStatus.SENT if success else EmailStatus.FAILED

        self.logs.append(EmailLog(
            log_id=f"LOG-{self._counter:04d}",
            order_id=order_id,
            timestamp=datetime.now().isoformat(),
            status=status.value,
            recipient=email_data["to"],
            subject=email_data["subject"],
            details=f"{'Simulated' if EMAIL_CONFIG['simulation_mode'] else 'SMTP'} "
                    f"— {'Success' if success else 'Failed'}"
        ))

        return {
            "success": success,
            "status": status.value,
            "message": f"Email {'sent' if success else 'FAILED'} to {email_data['to']}",
            "sent_at": datetime.now().isoformat() if success else ""
        }

    def _simulate(self, email_data: Dict) -> bool:
        """Simulate sending — always succeeds in demo mode."""
        return True

    def _real_send(self, email_data: Dict) -> bool:
        """Send via real SMTP."""
        try:
            msg = MIMEMultipart()
            msg['From'] = email_data["from"]
            msg['To'] = email_data["to"]
            msg['Subject'] = email_data["subject"]
            msg.attach(MIMEText(email_data["body"], 'plain'))
            server = smtplib.SMTP(EMAIL_CONFIG['smtp_server'],
                                  EMAIL_CONFIG['smtp_port'])
            if EMAIL_CONFIG['use_tls']:
                server.starttls()
            server.send_message(msg)
            server.quit()
            return True
        except Exception:
            return False

    def get_logs(self) -> List[Dict]:
        return [asdict(l) for l in self.logs]
